apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: nagp-k8s
spec:
  ports:
  - port: 5432
    name: user-db
  clusterIP: None # To not exposed outside cluster
  selector:
    app: user-db
