apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  namespace: nagp-k8s
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: nagp-k8s-persistent-disk
    fsType: ext4